export enum ENAV_BAR_CODE {
  DASHBOARD = 'DASHBOARD',
  ACCOUNT = 'ACCOUNT',
  EXAM_SYSTEM = 'EXAM_SYSTEM',
  EXAM_CUSTOM = 'EXAM_CUSTOM',
  NEWS = 'NEWS',
  CHATBOT = 'CHATBOT',
  LIBRARY = 'LIBRARY',
}
