export const QUERY_KEYS = {
  CHAT_BOT: {
    LIST: 'CHAT_BOT_LIST',
    SELECT: 'CHAT_BOT_SELECT',
  },
  ACCOUNT: {
    USER_INFO: 'USER_INFO',
    LIST: 'ACCOUNT_LIST',
    NAME: 'ACCOUNT_NAME',
  },
  EXAM: {
    LIST: 'EXAM_LIST',
    DESIGN_LIST: 'EXAM_DESIGN_LIST',
    SELECT: 'EXAM_SELECT',
  },
  SCHOOL_SUBJECT: {
    LIST: 'SCHOOL_SUBJECT_LIST',
  },
  GROUP: {
    LIST: 'GROUP_LIST',
    SELECT: 'GROUP_SELECT',
    EXAM_IN_GROUP: 'EXAM_IN_GROUP',
    CHATBOT_IN_GROUP: 'CHATBOT_IN_GROUP',
  },
  NEWS: {
    ALL: 'ALL',
    DETAIL: 'DETAIL',
    CATEGORY: 'CATEGORY',
  },
  CONCLUSION: {
    LIST: 'CONCLUSION_LIST',
  },
  DICTIONARY: {
    LIST: 'DICTIONARY',
    GROUPS: 'GROUPS',
  },
  REPORT: {
    STATISTICS: 'STATISTICS',
    SCORES: 'SCORE',
  },
  DO_EXAM: {
    LIST: 'DO_EXAM_LIST',
  },
};
