export const examDummmyData = [
  {
    _id: '66091e19a2d99a0e298a7e64',
    type: 'R',
    createAt: 1725343479,
    updateAt: 1725343479,
    creator: 'Phương Tiên',
    updator: 'Phương Tiên',
    status: 'ACTIVE',
    questions: [
      {
        questionTitle: 'Bạn có nhiều sở thích liên quan đến nhóm KỸ THUẬT? Hãy chọn một hoặc nhiều đáp án gần giống với bạn nhất nhé!',
        questionType: 'TICK_BOX',
        image: '',
        options: [
          {
            image: '',
            content: 'Tôi thích làm các công việc thủ công như cắt may, xếp giấy, đan, móc, khắc chữ...',
            isResult: false,
            _id: '66091e19a2d99a0e298a7e66',
          },
          {
            image: '',
            content: 'Tôi thích trang điểm; chăm chút, làm đẹp cho bản thân và người…',
            isResult: false,
            _id: '66091e19a2d99a0e298a7e67',
          },
          {
            image: '',
            content: 'Tôi thích chăm sóc, cắt tỉa cây cảnh.',
            isResult: false,
            _id: '66091e19a2d99a0e298a7e68',
          },
          {
            image: '',
            content: 'Tôi thích suy nghĩ về những vấn đề phức tạp, làm công việc phức tạp.',
            isResult: false,
            _id: '66091e19a2d99a0e298a7e69',
          },
          {
            image: '',
            content: 'Tôi thích mày mò, sửa chữa các đồ vật bị hư hỏng.',
            isResult: false,
            _id: '66091e19a2d99a0e298a7e6a',
          },
          {
            image: '',
            content: 'Tôi thích khám phá cấu tạo bên trong của các đồ vật, máy móc, thiết bị.',
            isResult: false,
            _id: '66091e19a2d99a0e298a7e6b',
          },
          {
            image: '',
            content: 'Tôi thích làm việc ngoài trời với không gian mở hơn là bên trong phòng học kín.',
            isResult: false,
            _id: '66091e19a2d99a0e298a7e6c',
          },
          {
            image: '',
            content: 'Tôi là người độc lập và thích làm việc một mình.',
            isResult: false,
            _id: '66091e19a2d99a0e298a7e6d',
          },
          {
            image: '',
            content: 'Tôi thích làm những việc có thể hoàn thành bằng tay chân (cho dù yêu cầu tỉ mỉ) hơn là những công việc phải suy nghĩ nhiều.',
            isResult: false,
            _id: '66091e19a2d99a0e298a7e6e',
          },
          {
            image: '',
            content: 'Tôi hay tò mò về bất cứ thứ gì xung quanh mình (Thiên nhiên, khoa học kỹ thuật, không gian;...)',
            isResult: false,
            _id: '66091e19a2d99a0e298a7e6f',
          },
          {
            image: '',
            content: 'Tôi không phải người hoạt ngôn, dễ hòa nhập với môi trường mới.',
            isResult: false,
            _id: '66091e19a2d99a0e298a7e70',
          },
        ],
        _id: '66091e19a2d99a0e298a7e65',
      },
    ],
    results: [
      {
        score: null,
        content:
          '<article>\n        <h3>R - Realistic - Kỹ thuật</h3>\n        <p>Người yêu thích Kỹ thuật thường thực tế, thích khám phá, thao tác một cách trật tự và có hệ thống, thích làm việc với những vật cụ thể như máy móc, công cụ dụng cụ, con vật,…</p>\n        <p>\n            <div>\n            <strong>Năng lực nổi trội: </strong>thủ công, cơ khí, nông nghiệp, điện, kỹ thuật,…\n            </div>\n            <div>\n            <strong>Năng lượng thiếu hụt: </strong>Xã hội và Giáo dục.\n            </div>\n        </p>\n    </article>',
        image: 'https://huongnghiepaau.edu.vn/wp-content/uploads/2022/07/nhom-ky-thuat-228x250.jpg',
        _id: '66091e19a2d99a0e298a7e71',
        detail: 'https://huongnghiepaau.edu.vn/nhom-ky-thuat-realistic',
      },
    ],
  },
  {
    _id: '66091e5ea2d99a0e298a7e81',
    type: 'I',
    createAt: 1725343479,
    updateAt: 1725343479,
    creator: 'Phương Tiên',
    updator: 'Phương Tiên',
    status: 'ACTIVE',
    questions: [
      {
        questionTitle: 'Bạn có nhiều sở thích liên quan đến nhóm NGHIÊN CỨU? Hãy chọn một hoặc nhiều đáp án gần giống với bạn nhất nhé!',
        questionType: 'TICK_BOX',
        image: '',
        options: [
          {
            image: '',
            content: 'Tôi tò mò và thích tìm hiểu về mọi thứ xung quanh (Thiên nhiên, khoa học kỹ thuật, không gian;...)',
            isResult: false,
            _id: '66091e5ea2d99a0e298a7e83',
          },
          {
            image: '',
            content: 'Tôi thích học Văn nghị luận, phân tích và lập luận các vấn đề.',
            isResult: false,
            _id: '66091e5ea2d99a0e298a7e84',
          },
          {
            image: '',
            content: 'Tôi thích chăm sóc, cắt tỉa cây cảnh.',
            isResult: false,
            _id: '66091e5ea2d99a0e298a7e85',
          },
          {
            image: '',
            content: 'Tôi thích suy nghĩ về những vấn đề phức tạp, làm công việc phức tạp.',
            isResult: false,
            _id: '66091e5ea2d99a0e298a7e86',
          },
          {
            image: '',
            content: 'Tôi thích thực hành thí nghiệm và nghiên cứu.',
            isResult: false,
            _id: '66091e5ea2d99a0e298a7e87',
          },
          {
            image: '',
            content: 'Tôi thích đọc những thể loại sách về khoa học, lịch sử, văn hoá.',
            isResult: false,
            _id: '66091e5ea2d99a0e298a7e88',
          },
          {
            image: '',
            content: 'Tôi thích giải những đề toán phức tạp, có độ khó cao.',
            isResult: false,
            _id: '66091e5ea2d99a0e298a7e89',
          },
          {
            image: '',
            content: 'Tôi thích các hoạt động liên quan đến điều tra, truy tìm manh mối.',
            isResult: false,
            _id: '66091e5ea2d99a0e298a7e8a',
          },
          {
            image: '',
            content: 'Tôi thích đọc sách và xem phim chủ đề trinh thám, thám tử,...',
            isResult: false,
            _id: '66091e5ea2d99a0e298a7e8b',
          },
          {
            image: '',
            content: 'Tôi thích sưu tập một thứ gì đó (Tem, tiền xu, đá,...)',
            isResult: false,
            _id: '66091e5ea2d99a0e298a7e8c',
          },
          {
            image: '',
            content: 'Tôi thích các trò chơi ô chữ, giải đố;...',
            isResult: false,
            _id: '66091e5ea2d99a0e298a7e8d',
          },
        ],
        _id: '66091e5ea2d99a0e298a7e82',
      },
    ],
    results: [
      {
        score: null,
        content:
          '<article>\n        <h3>I - Investigate - Nghiên cứu</h3>\n        <p>Người có sở thích nổi trội ở nhóm Nghiên cứu thường thích phân tích, nghiên cứu sâu mọi vấn đề. Họ cũng hay tò mò, thích quan sát, học hỏi, điều tra, đánh giá và giải quyết các vấn đề.</p>\n        <p> \n            <div>\n            <strong>Năng lực nổi trội: </strong>khoa học, toán học, tư duy phản biện, phân tích,…\n            </div>\n            <div>\n            <strong>Năng lượng thiếu hụt: </strong>khả năng thuyết phục, tương tác xã hội và những hoạt động lặp đi lặp lại.\n            </div>\n        </p>\n    </article>',
        image: 'https://huongnghiepaau.edu.vn/wp-content/uploads/2022/07/nhom-nghien-cuu-228x250.jpg',
        _id: '66091e5ea2d99a0e298a7e8e',
        detail: 'https://huongnghiepaau.edu.vn/nhom-nghien-cuu-investigative',
      },
    ],
  },
  {
    _id: '66092074a2d99a0e298a7eab',
    type: 'A',
    createAt: 1725343479,
    updateAt: 1725343479,
    creator: 'Phương Tiên',
    updator: 'Phương Tiên',
    status: 'UNACTIVATED',
    questions: [
      {
        questionTitle: 'Bạn có nhiều sở thích liên quan đến nhóm NGHỆ THUẬT? Hãy chọn một hoặc nhiều đáp án gần giống với bạn nhất nhé!',
        questionType: 'TICK_BOX',
        image: '',
        options: [
          {
            image: '',
            content: 'Tôi là người đa sầu đa cảm, dễ xúc động và không giỏi kiềm chế cảm xúc.',
            isResult: false,
            _id: '66092074a2d99a0e298a7ead',
          },
          {
            image: '',
            content: 'Tôi có trí tưởng tượng vô cùng phong phú.',
            isResult: false,
            _id: '66092074a2d99a0e298a7eae',
          },
          {
            image: '',
            content: 'Tôi thích chăm sóc, cắt tỉa cây cảnh.',
            isResult: false,
            _id: '66092074a2d99a0e298a7eaf',
          },
          {
            image: '',
            content: 'Tôi thích cuộc sống tự do, không bị bó buộc và khuôn khổ hay quy tắc nào.',
            isResult: false,
            _id: '66092074a2d99a0e298a7eb0',
          },
          {
            image: '',
            content: 'Tôi thích các hoạt động văn nghệ như ca hát, diễn xuất, MC,...',
            isResult: false,
            _id: '66092074a2d99a0e298a7eb1',
          },
          {
            image: '',
            content: 'Tôi thích chụp hình, vẽ tranh, trang trí, điêu khắc;...',
            isResult: false,
            _id: '66092074a2d99a0e298a7eb2',
          },
          {
            image: '',
            content: 'Tôi thích tự thiết kế hoặc tự chọn; phối quần áo cho mình và người khác.',
            isResult: false,
            _id: '66092074a2d99a0e298a7eb3',
          },
          {
            image: '',
            content: 'Tôi không thích làm những công việc rập khuôn, lập đi lập lại nhiều lần, không có sự sáng tạo..',
            isResult: false,
            _id: '66092074a2d99a0e298a7eb4',
          },
          {
            image: '',
            content: 'Tôi thích âm nhạc và không thể sống nếu thiếu chúng.',
            isResult: false,
            _id: '66092074a2d99a0e298a7eb5',
          },
          {
            image: '',
            content: 'Tôi thích sưu tập một thứ gì đó (Tem, tiền xu, đá,...)',
            isResult: false,
            _id: '66092074a2d99a0e298a7eb6',
          },
          {
            image: '',
            content: 'Tôi dễ bị hấp dẫn bởi cái đẹp (Một gương mặt đẹp, một bức tranh đẹp, một bài hát hay,...)',
            isResult: false,
            _id: '66092074a2d99a0e298a7eb7',
          },
          {
            image: '',
            content: 'Tôi có một tâm hồn khá mơ mộng và tôi thích thế.',
            isResult: false,
            _id: '66092074a2d99a0e298a7eb8',
          },
        ],
        _id: '66092074a2d99a0e298a7eac',
      },
    ],
    results: [
      {
        score: null,
        content:
          '<article>\n        <h3>A - Artistic - Nghệ thuật</h3>\n        <p>Người yêu thích Nghệ thuật thường có trí tưởng tượng phong phú, trực giác mạnh và khả năng sáng tạo tốt. Họ yêu thích cái đẹp và dễ   bị hấp dẫn bởi chúng. Đặc tính của người thuộc nhóm này là tự do, không có thiện cảm với những nguyên tắc, các công việc rõ ràng, hệ thống hóa.</p>\n        <p>\n            <div>\n            <strong>Năng lực nổi trội: </strong>nghệ thuật (ngôn ngữ viết – nói, hội họa, ca hát, trình diễn, diễn xuất,…)\n            </div>\n            <div>\n            <strong>Năng lượng thiếu hụt: </strong>nghiệp vụ hành chính, kinh doanh.\n            </div>\n        </p>\n    </article>',
        image: 'https://huongnghiepaau.edu.vn/wp-content/uploads/2022/07/nhom-nghe-thuat-228x250.jpg',
        _id: '66092074a2d99a0e298a7eb9',
        detail: 'https://huongnghiepaau.edu.vn/nhom-nghe-thuat-artistic',
      },
    ],
  },
  {
    _id: '66092358a2d99a0e298a7ef4',
    type: 'S',
    createAt: 1725343479,
    updateAt: 1725343479,
    creator: 'Phương Tiên',
    updator: 'Phương Tiên',
    status: 'UNACTIVATED',
    questions: [
      {
        questionTitle: 'Bạn có nhiều sở thích liên quan đến nhóm XÃ HỘI? Hãy chọn một hoặc nhiều đáp án gần giống với bạn nhất nhé!',
        questionType: 'TICK_BOX',
        image: '',
        options: [
          {
            image: '',
            content: 'Tôi là người khá thân thiện và thoải mái trong việc giúp đỡ mọi người xung quanh.',
            isResult: false,
            _id: '66092358a2d99a0e298a7ef6',
          },
          {
            image: '',
            content: 'Tôi thích gặp gỡ và làm quen nhiều bạn mới.',
            isResult: false,
            _id: '66092358a2d99a0e298a7ef7',
          },
          {
            image: '',
            content: 'Tôi thích khuyên bảo hay trở thành người hoà giải khi có mâu thuẫn xảy ra trong nhóm bạn của mình.',
            isResult: false,
            _id: '66092358a2d99a0e298a7ef8',
          },
          {
            image: '',
            content: 'Tôi tự thấy mình luôn biết cách cư xử lịch thiệp và tử tế.',
            isResult: false,
            _id: '66092358a2d99a0e298a7ef9',
          },
          {
            image: '',
            content: 'Tôi thích tham gia các hoạt động thiện nguyện vì cộng đồng.',
            isResult: false,
            _id: '66092358a2d99a0e298a7efa',
          },
          {
            image: '',
            content: 'Tôi thích kể chuyện; pha trò làm cho mọi người xung quanh cảm thấy thoải mái và vui vẻ.',
            isResult: false,
            _id: '66092358a2d99a0e298a7efb',
          },
          {
            image: '',
            content: 'Tôi thích tự thiết kế hoặc tự chọn; phối quần áo cho mình và người khác.',
            isResult: false,
            _id: '66092358a2d99a0e298a7efc',
          },
          {
            image: '',
            content: 'Tôi thích lắng nghe bạn bè chia sẻ về những vấn đề cá nhân của họ.',
            isResult: false,
            _id: '66092358a2d99a0e298a7efd',
          },
          {
            image: '',
            content: 'Tôi thích hoạt động nhóm, thích chơi những môn thể thao mang tính chất đồng đội.',
            isResult: false,
            _id: '66092358a2d99a0e298a7efe',
          },
          {
            image: '',
            content: 'Tôi thích sưu tập một thứ gì đó (Tem, tiền xu, đá,...)',
            isResult: false,
            _id: '66092358a2d99a0e298a7eff',
          },
          {
            image: '',
            content: 'Tôi thoải mái khi tham gia các hoạt động đông người, dễ dàng hoà nhập với đám đông.',
            isResult: false,
            _id: '66092358a2d99a0e298a7f00',
          },
          {
            image: '',
            content: 'Tôi có nhiều bạn bè và tôi thích việc thường xuyên liên lạc hay tương tác với họ qua mạng xã hội..',
            isResult: false,
            _id: '66092358a2d99a0e298a7f01',
          },
        ],
        _id: '66092358a2d99a0e298a7ef5',
      },
    ],
    results: [
      {
        score: null,
        content:
          '<article>\n        <h3>S - Social - Xã hội</h3>\n        <p>Nhóm Xã hội là sở thích của những bạn thích làm việc và tương tác với người khác bao gồm những công việc thường xuyên tiếp xúc và giao tiếp với xã hội như giao tiếp, huấn luyện, chữa lành, thiện nguyện, công tác xã hội,… Nhóm này thường có thiện cảm với các công việc rõ ràng, có hệ thống liên quan đến vật liệu, công cụ hoặc máy móc.</p>\n        <p>\n            <div>\n            <strong>Năng lực nổi trội: </strong>giao tiếp, giáo dục.\n            </div>\n            <div>\n            <strong>Năng lượng thiếu hụt: </strong>thủ công, kỹ thuật.\n            </div>\n        </p>\n    </article>',
        image: 'https://huongnghiepaau.edu.vn/wp-content/uploads/2022/07/nhom-xa-hoi-228x250.jpg',
        _id: '66092358a2d99a0e298a7f02',
        detail: 'https://huongnghiepaau.edu.vn/nhom-xa-hoi-social',
      },
    ],
  },
  {
    _id: '660924d8a2d99a0e298a7f8c',
    type: 'E',
    questionType: 'TICK_BOX',
    createAt: 1725343479,
    updateAt: 1725343479,
    creator: 'Phương Tiên',
    updator: 'Phương Tiên',
    status: 'UNACTIVATED',
    questions: [
      {
        questionTitle: 'Bạn có nhiều sở thích liên quan đến nhóm QUẢN LÝ? Hãy chọn một hoặc nhiều đáp án gần giống với bạn nhất nhé!',
        questionType: 'TICK_BOX',
        image: '',
        options: [
          {
            image: '',
            content: 'Tôi thích được trở thành người lãnh đạo trong nhóm; trong lớp hoặc trong các tổ chức.',
            isResult: false,
            _id: '660924d8a2d99a0e298a7f8e',
          },
          {
            image: '',
            content: 'Tôi có tính háu thắng, thích cạnh tranh và thích mình phải giỏi hơn người khác.',
            isResult: false,
            _id: '660924d8a2d99a0e298a7f8f',
          },
          {
            image: '',
            content: 'Tôi thích tham gia vào các cuộc tranh luận và thuyết phục người khác.',
            isResult: false,
            _id: '660924d8a2d99a0e298a7f90',
          },
          {
            image: '',
            content: 'Tôi thường xuyên đặt ra các mục tiêu, kế hoạch trong cuộc sống.',
            isResult: false,
            _id: '660924d8a2d99a0e298a7f91',
          },
          {
            image: '',
            content: 'Tôi là người rất quyết đoán, khó mà thay đổi được suy nghĩ của tôi.',
            isResult: false,
            _id: '660924d8a2d99a0e298a7f92',
          },
          {
            image: '',
            content: 'Tôi có suy nghĩ sau này sẽ trở thành chủ một doanh nghiệp nhỏ.',
            isResult: false,
            _id: '660924d8a2d99a0e298a7f93',
          },
          {
            image: '',
            content: 'Tôi thích mạo hiểm và hào hứng khi được tham gia các cuộc phiêu mới.',
            isResult: false,
            _id: '660924d8a2d99a0e298a7f94',
          },
          {
            image: '',
            content: 'Tôi cầu toàn và muốn làm công việc cho đến khi hoàn tất, không thích bỏ dở giữa chừng.',
            isResult: false,
            _id: '660924d8a2d99a0e298a7f95',
          },
          {
            image: '',
            content: 'Tôi thích tiết kiệm và quản lý tốt tiền bạc của mình.',
            isResult: false,
            _id: '660924d8a2d99a0e298a7f96',
          },
          {
            image: '',
            content: 'Tôi thích việc lên kế hoạch, tổ chức, quản lý hay tổng hợp công việc của những thành viên khác trong nhóm.',
            isResult: false,
            _id: '660924d8a2d99a0e298a7f97',
          },
        ],
        _id: '660924d8a2d99a0e298a7f8d',
      },
    ],
    results: [
      {
        score: null,
        content:
          '<article>\n        <h3>E - Enterprising - Quản lý</h3>\n        <p>Người yêu thích Quản lý thường yêu thích các hoạt động đòi hỏi sự lãnh đạo, thuyết phục, tác động vào người khác để đạt được mục đích chung của tổ chức hoặc lợi ích kinh tế. Nhóm này thường ưu tiên những công việc bao quát, những cải tiến, đổi mới mà không thích làm việc một cách máy móc, tượng trưng.</p>\n        <p>\n            <div>\n            <strong>Năng lực nổi trội: </strong>lãnh đạo, giao tiếp, thuyết phục.\n            </div>\n            <div>\n            <strong>Năng lượng thiếu hụt: </strong>khoa học.\n            </div>\n        </p>\n    </article>',
        image: 'https://huongnghiepaau.edu.vn/wp-content/uploads/2022/07/nhom-quan-ly-228x250.jpg',
        _id: '660924d8a2d99a0e298a7f98',
        detail: 'https://huongnghiepaau.edu.vn/nhom-quan-ly-enterprising',
      },
    ],
  },
  {
    _id: '660925b8a2d99a0e298a7f9a',
    type: 'C',
    createAt: 1725343479,
    updateAt: 1725343479,
    creator: 'Phương Tiên',
    updator: 'Phương Tiên',
    status: 'ACTIVE',
    questions: [
      {
        questionTitle: 'Bạn có nhiều sở thích liên quan đến nhóm NGHIỆP VỤ? Hãy chọn một hoặc nhiều đáp án gần giống với bạn nhất nhé!',
        questionType: 'TICK_BOX',
        image: '',
        options: [
          {
            image: '',
            content: 'Tôi thích mọi thứ được sắp xếp gọn gàng và ngăn nắp.',
            isResult: false,
            _id: '660925b8a2d99a0e298a7f9c',
          },
          {
            image: '',
            content: 'Tôi thường xuyên lập danh sách chi tiết các công việc cần làm trong ngày hoặc trong một thời gian ngắn.',
            isResult: false,
            _id: '660925b8a2d99a0e298a7f9d',
          },
          {
            image: '',
            content: 'Tôi thích đánh máy các tài liệu hơn là viết tay.',
            isResult: false,
            _id: '660925b8a2d99a0e298a7f9e',
          },
          {
            image: '',
            content: 'Tôi rất thực tế, luôn cân nhắc kỹ về chi phí trước khi mua một thứ gì đó.',
            isResult: false,
            _id: '660925b8a2d99a0e298a7f9f',
          },
          {
            image: '',
            content: 'Tôi thích đảm nhiệm vị trí thư ký trong các buổi họp hay họp nhóm.',
            isResult: false,
            _id: '660925b8a2d99a0e298a7fa0',
          },
          {
            image: '',
            content: 'Tôi yêu thích việc sắp xếp, tổ chức công việc cho bản thân hoặc nhóm.',
            isResult: false,
            _id: '660925b8a2d99a0e298a7fa1',
          },
          {
            image: '',
            content: 'Tôi tự thấy mình là người tỉ mỉ, chu đáo và cẩn thận.',
            isResult: false,
            _id: '660925b8a2d99a0e298a7fa2',
          },
          {
            image: '',
            content: 'Tôi thích công việc tính toán sổ sách, ghi chép số liệu.',
            isResult: false,
            _id: '660925b8a2d99a0e298a7fa3',
          },
          {
            image: '',
            content: 'Tôi thích các công việc lưu trữ, phân loại và cập nhật thông tin.',
            isResult: false,
            _id: '660925b8a2d99a0e298a7fa4',
          },
          {
            image: '',
            content: 'Tôi thực sự bị cuốn hút bởi các hàm tính toán trong excel.',
            isResult: false,
            _id: '660925b8a2d99a0e298a7fa5',
          },
        ],
        _id: '660925b8a2d99a0e298a7f9b',
      },
    ],
    results: [
      {
        score: null,
        content:
          '<article>\n        <h3>C - Conventional - Nghiệp vụ</h3>\n        <p>Người yêu thích Quản lý thường yêu thích các hoạt động đòi hỏi sự lãnh đạo, thuyết phục, tác động vào người khác để đạt được mục đích chung của tổ chức hoặc lợi ích kinh tế. Nhóm này thường ưu tiên những công việc bao quát, những cải tiến, đổi mới mà không thích làm việc một cách máy móc, tượng trưng.</p>\n        <p>\n            <div>\n            <strong>Năng lực nổi trội: </strong>lãnh đạo, giao tiếp, thuyết phục.\n            </div>\n            <div>\n            <strong>Năng lượng thiếu hụt: </strong>khoa học.\n            </div>\n        </p>\n    </article>',
        image: 'https://huongnghiepaau.edu.vn/wp-content/uploads/2022/07/nhom-nghiep-vu-228x250.jpg',
        _id: '660925b8a2d99a0e298a7fa6',
        detail: 'https://huongnghiepaau.edu.vn/nhom-nghiep-vu-conventional',
      },
    ],
  },
  {
    _id: '660ed9489f5e9ba31cdfbf7c',
    type: 'EQ',
    createAt: 1725343479,
    updateAt: 1725343479,
    creator: 'Phương Tiên',
    updator: 'Phương Tiên',
    status: 'BLOCKED',
    questions: [
      {
        questionTitle: '1. Khi đang ngồi trên máy bay, đột nhiên máy bay rung động rất mạnh và lắc lư qua trái phải. Lúc đó, bạn sẽ làm gì?',
        questionType: 'MULTIPLE_CHOICE',
        image: '',
        options: [
          {
            image: '',
            content: 'A. Tiếp tục xem điện thoại, không quan tâm.',
            isResult: false,
            standardScore: 20,
            _id: '660ed9489f5e9ba31cdfbf7e',
          },
          {
            image: '',
            content: 'B. Quan sát tình hình thay đổi, cẩn thận lắng nghe thông báo từ tiếp viên.',
            isResult: false,
            standardScore: 20,
            _id: '660ed9489f5e9ba31cdfbf7f',
          },
          {
            image: '',
            content: 'C. Cả A và B đều đúng.',
            isResult: false,
            standardScore: 20,
            _id: '660ed9489f5e9ba31cdfbf80',
          },
          {
            image: '',
            content: 'D. Tôi không biết, tôi không quan tâm.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf81',
          },
        ],
        _id: '660ed9489f5e9ba31cdfbf7d',
      },
      {
        questionTitle: '2. Có 1 đứa trẻ trong nhóm 4 đứa mà bạn đang trông nom khóc vì không ai chơi cùng. Bạn sẽ làm gì lúc này?',
        image: '',
        options: [
          {
            image: '',
            content: 'A. Không quan tâm.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf83',
          },
          {
            image: '',
            content: 'B. Trò chuyện, tìm cách giúp đứa trẻ.',
            isResult: false,
            standardScore: 20,
            _id: '660ed9489f5e9ba31cdfbf84',
          },
          {
            image: '',
            content: 'C. Nhắc nhở bé nín khóc.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf85',
          },
          {
            image: '',
            content: 'D. Cho bé đồ chơi.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf86',
          },
        ],
        _id: '660ed9489f5e9ba31cdfbf82',
      },
      {
        questionTitle:
          '3. Bạn là sinh viên và muốn đạt điểm cao ở môn học A, nhưng kết quả bài thi giữa kỳ môn đó chỉ ở mức trung bình. Bạn sẽ làm gì?',
        image: '',
        options: [
          {
            image: '',
            content: 'A. Lập kế hoạch học tập và quyết tâm thực hiện.',
            isResult: false,
            standardScore: 20,
            _id: '660ed9489f5e9ba31cdfbf88',
          },
          {
            image: '',
            content: 'B. Sau này sẽ học tập chăm chỉ hơn.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf89',
          },
          {
            image: '',
            content: 'C. Khích lệ bản thân: môn này không tốt thì tập trung vào môn học khác.',
            isResult: false,
            standardScore: 20,
            _id: '660ed9489f5e9ba31cdfbf8a',
          },
          {
            image: '',
            content: 'D. Thuyết phục giảng viên cho điểm cao hơn.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf8b',
          },
        ],
        _id: '660ed9489f5e9ba31cdfbf87',
      },
      {
        questionTitle:
          '4. Bạn là nhân viên bán bảo hiểm và đang tìm kiếm khách hàng mới. Cả 15 người bạn trao đổi đều không có thái độ rõ ràng hoặc không muốn hợp tác. Lúc đó, bạn sẽ làm gì?',
        image: '',
        options: [
          {
            image: '',
            content: 'A. Nghĩ chuyện này chỉ xảy ra hôm nay, hy vọng ngày mai sẽ may mắn hơn.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf8d',
          },
          {
            image: '',
            content: 'B. Xem xét lại mình có phù hợp với công việc không.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf8e',
          },
          {
            image: '',
            content: 'C. Cố gắng hơn ở buổi gặp sau, duy trì thái độ làm việc siêng năng.',
            isResult: false,
            standardScore: 20,
            _id: '660ed9489f5e9ba31cdfbf8f',
          },
          {
            image: '',
            content: 'D. Bỏ qua 15 người này và tìm khách hàng khác.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf90',
          },
        ],
        _id: '660ed9489f5e9ba31cdfbf8c',
      },
      {
        questionTitle:
          '5. Bạn là giám đốc và đưa ra quy định không được phân biệt chủng tộc trong công ty. Một hôm, bạn vô tình nghe thấy có người pha trò về vấn đề này. Bạn sẽ giải quyết như thế nào?',
        image: '',
        options: [
          {
            image: '',
            content: 'A. Mặc kệ, đó chỉ là trò đùa.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf92',
          },
          {
            image: '',
            content: 'B. Gọi người đó vào phòng và mắng anh ta.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf93',
          },
          {
            image: '',
            content: 'C. Ngay lập tức nói với anh ta rằng công ty không chấp nhận những trò đùa như vậy.',
            isResult: false,
            standardScore: 20,
            _id: '660ed9489f5e9ba31cdfbf94',
          },
          {
            image: '',
            content: 'D. Khuyên người đó tham gia khóa học chống phân biệt chủng tộc.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf95',
          },
        ],
        _id: '660ed9489f5e9ba31cdfbf91',
      },
      {
        questionTitle:
          '6. Bạn thân bạn đang lái xe thì đột nhiên bị xe của người khác tông vào, khiến anh ấy rất tức giận. Bạn sẽ làm gì để anh bạn ấy bình tĩnh trở lại?',
        image: '',
        options: [
          {
            image: '',
            content: 'A. Khuyên ngăn anh ấy bỏ qua. Không ai bị thương, không có vấn đề gì lớn.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf97',
          },
          {
            image: '',
            content: 'B. Chuyển sự chú ý bằng một bài hát anh ấy thích.',
            isResult: false,
            standardScore: 5,
            _id: '660ed9489f5e9ba31cdfbf98',
          },
          {
            image: '',
            content: 'C. Cùng anh ấy đổ lỗi cho người lái xe kia, thể hiện rằng bạn đứng về phía anh ấy.',
            isResult: false,
            standardScore: 5,
            _id: '660ed9489f5e9ba31cdfbf99',
          },
          {
            image: '',
            content:
              'D. Kể với anh ấy trải nghiệm tương tự của bạn. Lúc đó bạn cũng rất tức giận, nhưng sau đó bạn thấy tài xế bị tai nạn và được đưa đi cấp cứu.',
            isResult: false,
            standardScore: 20,
            _id: '660ed9489f5e9ba31cdfbf9a',
          },
        ],
        _id: '660ed9489f5e9ba31cdfbf96',
      },
      {
        questionTitle:
          '7. Bạn và chồng/vợ mâu thuẫn dẫn đến cãi nhau gay gắt. Trong lúc nóng nảy, cả hai đã xô xát với nhau, dù hai bạn thực sự không muốn. Lúc đó, bạn sẽ làm gì?',
        image: '',
        options: [
          {
            image: '',
            content: 'A. Im lặng 20 phút sau đó tiếp tục tranh luận.',
            isResult: false,
            standardScore: 20,
            _id: '660ed9489f5e9ba31cdfbf9c',
          },
          {
            image: '',
            content: 'B. Ngừng tranh cãi, im lặng mặc cho dù đối phương nói gì.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf9d',
          },
          {
            image: '',
            content: 'C. Xin lỗi đối phương và yêu cầu anh ấy/cô ấy xin lỗi.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf9e',
          },
          {
            image: '',
            content: 'D. Dừng lại sắp xếp suy nghĩ, sau đó trình bày quan điểm của bạn.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbf9f',
          },
        ],
        _id: '660ed9489f5e9ba31cdfbf9b',
      },
      {
        questionTitle: '8. Bạn là trưởng bộ phận và muốn đề xuất biện pháp để giải quyết các vấn đề trong công việc. Vậy bạn sẽ làm gì trước tiên?',
        image: '',
        options: [
          {
            image: '',
            content: 'A. Sắp xếp lịch họp mỗi ngày để tối đa hóa thời gian thảo luận với mọi người.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbfa1',
          },
          {
            image: '',
            content: 'B. Cho mọi người thời gian để tìm hiểu nhau.',
            isResult: false,
            standardScore: 20,
            _id: '660ed9489f5e9ba31cdfbfa2',
          },
          {
            image: '',
            content: 'C. Yêu cầu từng người chia sẻ cách giải quyết vấn đề.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbfa3',
          },
          {
            image: '',
            content: 'D. Khuyến khích mọi người chia sẻ nhiều ý tưởng sáng tạo.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbfa4',
          },
        ],
        _id: '660ed9489f5e9ba31cdfbfa0',
      },
      {
        questionTitle: '9. Con trai 3 tuổi của bạn rất nhút nhát. Bé sợ người lạ và sợ đến những nơi xa lạ. Bạn sẽ làm gì?',
        image: '',
        options: [
          {
            image: '',
            content: 'A. Chấp nhận tính nhút nhát của trẻ, xem xét cách để bé tránh được những nơi cảm thấy không được thoải mái.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbfa6',
          },
          {
            image: '',
            content: 'B. Đưa con đến gặp chuyên gia tâm lý.',
            isResult: false,
            standardScore: 5,
            _id: '660ed9489f5e9ba31cdfbfa7',
          },
          {
            image: '',
            content: 'C. Cố tình đưa con đi gặp nhiều người, đến những nơi xa lạ để con vượt qua nỗi sợ.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbfa8',
          },
          {
            image: '',
            content: 'D. Lên kế hoạch cho con học cách đối phó với người lạ theo mức độ tăng dần.',
            isResult: false,
            standardScore: 20,
            _id: '660ed9489f5e9ba31cdfbfa9',
          },
        ],
        _id: '660ed9489f5e9ba31cdfbfa5',
      },
      {
        questionTitle: '10. Bạn muốn bắt đầu học lại loại nhạc cụ đã từng học khi còn nhỏ. Bạn sẽ làm gì để tận dụng tối đa thời gian?',
        image: '',
        options: [
          {
            image: '',
            content: 'A. Luyện tập đều đặn mỗi ngày.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbfab',
          },
          {
            image: '',
            content: 'B. Lựa chọn bản nhạc có thể cải thiện khả năng của bạn để luyện tập.',
            isResult: false,
            standardScore: 20,
            _id: '660ed9489f5e9ba31cdfbfac',
          },
          {
            image: '',
            content: 'C. Chỉ tập nếu có hứng thú.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbfad',
          },
          {
            image: '',
            content: 'D. Chọn bản nhạc khó hơn so với khả năng những nếu bạn luyện tập nhiều thì vẫn chơi được.',
            isResult: false,
            standardScore: 0,
            _id: '660ed9489f5e9ba31cdfbfae',
          },
        ],
        _id: '660ed9489f5e9ba31cdfbfaa',
      },
    ],
    results: [
      {
        score: [0, 60],
        content:
          'Bạn khá lạnh lùng và ít khi quan tâm người khác nghĩ gì. Chính nhờ sự lạnh lùng đó giúp bạn ra quyết định một cách quyết đoán hơn, nhưng đôi khi lại hay làm buồn lòng người khác mặc dù bạn không hề cố ý.',
        image: '',
        _id: '660ed9489f5e9ba31cdfbfaf',
      },
      {
        score: [61, 120],
        content:
          'Bạn có khả năng tương đối trong việc thấu hiểu người khác nghĩ gì, tuy nhiên việc bộc lộ cảm xúc của bạn cũng như diễn đạt qua nét mặt, cử chỉ còn nhiều khó khăn, nên bạn thường xuyên chọn cách im lặng. Khép mình trong thế giới nội tâm.',
        image: '',
        _id: '660ed9489f5e9ba31cdfbfb0',
      },
      {
        score: [121, 140],
        content:
          'Bạn có khả năng thấu hiểu người khác nghĩ gì và có thể ứng xử lại một cách phù hợp và tinh tế. Bạn luôn vui vẻ và lạc quan trong cuộc sống dẫu có đôi lúc tưởng chừng như rơi vào hố sâu tuyệt vọng nhưng bạn luôn có thể tự đúng lên và vượt qua một cách nhanh chóng.',
        image: '',
        _id: '660ed9489f5e9ba31cdfbfb1',
      },
      {
        score: [141, 200],
        content:
          'Bạn có khả năng thấu hiểu người khác cũng như chính bản thân bạn một cách sâu sắc. Bạn thường xuyên hoà mình, đồng cảm với cảm xúc của người khác, do vậy bạn có thể dễ dàng đọc được cảm xúc của họ, thậm chí động để chi phối cảm xúc của họ. Bạn rất lạc quan trong cuộc sống, kể cả những điểu tiêu cực nhất. Và một điều nữa: Bạn không có cách nào dừng sự mơ mộng của bản thân lại, trí tưởng tượng của bản thân luôn bay xa, bay mãi, và bạn thích điều đó.',
        image: '',
        _id: '660ed9489f5e9ba31cdfbfb2',
      },
    ],
  },
  {
    _id: '6611dc5bceba479b0ce476bf',
    type: 'IQ',
    createAt: 1725343479,
    updateAt: 1725343479,
    creator: 'Phương Tiên',
    updator: 'Phương Tiên',
    status: 'BLOCKED',
    questions: [
      {
        questionTitle: '1. Trước nửa đêm là bao nhiêu phút nếu trước đó 32 phút thời gian này gấp 3 lần số phút sau 22 giờ ?',
        questionType: 'MULTIPLE_CHOICE',
        options: [
          {
            content: 'A. 18 phút',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce476c1',
          },
          {
            content: 'B. 22 phút',
            isResult: true,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce476c2',
          },
          {
            content: 'C. 24 phút',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce476c3',
          },
          {
            content: 'D. 20 phút',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce476c4',
          },
        ],
        _id: '6611dc5bceba479b0ce476c0',
      },
      {
        questionTitle: '2. Tìm số thích hợp điền vào chỗ trống',
        image: 'https://i.imghippo.com/files/fMoSq1714665680.jpg',
        options: [
          {
            content: 'A. 7',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476c6',
          },
          {
            content: 'B. 8',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476c7',
          },
          {
            content: 'C. 6',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476c8',
          },
          {
            content: 'D. 9',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476c9',
          },
        ],
        _id: '6611dc5bceba479b0ce476c5',
      },
      {
        questionTitle: '3. Cho dãy số: 2 8 18 32 50 ? Số nào có thể thay vào chỗ có dấu hỏi chấm?',
        options: [
          {
            content: 'A. 60',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476cb',
          },
          {
            content: 'B. 70',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476cc',
          },
          {
            content: 'C. 64',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476cd',
          },
          {
            content: 'D. 72',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476ce',
          },
        ],
        _id: '6611dc5bceba479b0ce476ca',
      },
      {
        questionTitle: '4. Tìm số thích hợp có thể thay dấu hỏi chấm.',
        image: 'https://i.imghippo.com/files/pzvjP1714665854.jpg',
        options: [
          {
            content: 'A. 3',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476d0',
          },
          {
            content: 'B. 5',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476d1',
          },
          {
            content: 'C. 7',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476d2',
          },
          {
            content: 'D. 1',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476d3',
          },
        ],
        _id: '6611dc5bceba479b0ce476cf',
      },
      {
        questionTitle: '5. Hiện nay A gấp 3 lần tuổi B, sau 10 năm nữa B sẽ bằng phân nửa tuổi A. Vậy hiện nay tuổi của A là bao nhiêu?',
        options: [
          {
            content: 'A. 24 tuổi',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476d5',
          },
          {
            content: 'B. 30 tuổi',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476d6',
          },
          {
            content: 'C. 36 tuổi',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476d7',
          },
          {
            content: 'D. 40 tuổi',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476d8',
          },
        ],
        _id: '6611dc5bceba479b0ce476d4',
      },
      {
        questionTitle: '6. Mảnh ghép nào dưới đây trong số các mảnh A, B , C, D và E khi ghép với mảnh ở bên bên dưới cho ra hình vuông hoàn chỉnh?',
        image: 'https://i.imghippo.com/files/df2su1714702874.jpg',
        options: [
          {
            image: 'https://i.imghippo.com/files/PsNBc1714703010.jpg',
            content: 'A',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce476da',
          },
          {
            image: 'https://i.imghippo.com/files/lq6Dl1714703031.jpg',
            content: 'B',
            isResult: true,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce476db',
          },
          {
            image: 'https://i.imghippo.com/files/dv6pD1714703059.jpg',
            content: 'C',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce476dc',
          },
          {
            image: 'https://i.imghippo.com/files/2WvHE1714702982.jpg',
            content: 'D',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce476dd',
          },
        ],
        _id: '6611dc5bceba479b0ce476d9',
      },
      {
        questionTitle: '7. Hình nào khác với các hình còn lại?',
        image: 'https://i.imghippo.com/files/yy33C1714703175.jpg',
        options: [
          {
            content: 'A',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476df',
          },
          {
            content: 'B',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476e0',
          },
          {
            content: 'C',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476e1',
          },
          {
            content: 'D',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476e2',
          },
        ],
        _id: '6611dc5bceba479b0ce476de',
      },
      {
        questionTitle: '8. Hình nào khác với các hình còn lại?',
        image: 'https://i.imghippo.com/files/Zo5Ik1714703318.jpg',
        options: [
          {
            content: 'E',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476e4',
          },
          {
            content: 'B',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476e5',
          },
          {
            content: 'C',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476e6',
          },
          {
            content: 'D',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476e7',
          },
        ],
        _id: '6611dc5bceba479b0ce476e3',
      },
      {
        questionTitle: '9. Hình bên dưới còn thiếu hình nào trong các đáp án sau?',
        image: 'https://i.imghippo.com/files/ZoB5P1714703362.jpg',
        options: [
          {
            image: 'https://i.imghippo.com/files/CIK5c1714703527.jpg',
            content: 'A',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476e9',
          },
          {
            image: 'https://i.imghippo.com/files/giMod1714703545.jpg',
            content: 'B',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476ea',
          },
          {
            image: 'https://i.imghippo.com/files/gMSZ81714703506.jpg',
            content: 'C',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476eb',
          },
          {
            image: 'https://i.imghippo.com/files/ThALd1714703470.jpg',
            content: 'D',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476ec',
          },
        ],
        _id: '6611dc5bceba479b0ce476e8',
      },
      {
        questionTitle: '10. Số còn thiếu ở dấu chấm hỏi là số nào',
        image: 'https://i.imghippo.com/files/Soht11714703625.jpg',
        options: [
          {
            content: 'A. 4',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476ee',
          },
          {
            content: 'B. 18',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476ef',
          },
          {
            content: 'C. 24',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476f0',
          },
          {
            content: 'D. 1',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476f1',
          },
        ],
        _id: '6611dc5bceba479b0ce476ed',
      },
      {
        questionTitle: '11. Hình bên dưới còn thiếu hình nào trong các đáp án sau?',
        image: 'https://i.imghippo.com/files/qgsKB1714705987.jpg',
        options: [
          {
            image: 'https://i.imghippo.com/files/C3t3g1714706023.jpg',
            content: 'A',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476f3',
          },
          {
            image: 'https://i.imghippo.com/files/kYikQ1714706056.jpg',
            content: 'B',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476f4',
          },
          {
            image: 'https://i.imghippo.com/files/wACPQ1714706079.jpg',
            content: 'C',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476f5',
          },
          {
            image: 'https://i.imghippo.com/files/XpkhE1714706105.jpg',
            content: 'D',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476f6',
          },
        ],
        _id: '6611dc5bceba479b0ce476f2',
      },
      {
        questionTitle: '12. Hình vẽ nào còn thiếu trong chuỗi hình bên dưới',
        image: 'https://i.imghippo.com/files/UIKxj1714706349.png',
        options: [
          {
            content: 'A. Hình cuối cùng',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476f8',
          },
          {
            content: 'B. Hình đầu tiên',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476f9',
          },
          {
            content: 'C. Hình thứ 2 từ dưới tính lên',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476fa',
          },
          {
            content: 'D. Hình thứ 3 từ dưới tính lên',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce476fb',
          },
        ],
        _id: '6611dc5bceba479b0ce476f7',
      },
      {
        questionTitle:
          '13. Trong một gia đình có sáu thành viên A, B, C, D, E và F. A và B là một cặpvợ\nchồng, A là thành viên nam. D là con trai duy nhất của C. C là anh trai của A. E\nlà em gái của D. B là con dâu của F. F có chồng đã chết. Có bao nhiêu thành\nviên nam trong gia đình?',
        options: [
          {
            content: 'A. 2',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce476fd',
          },
          {
            content: 'B. 4',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce476fe',
          },
          {
            content: 'C. 3',
            isResult: true,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce476ff',
          },
          {
            content: 'D. 5',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce47700',
          },
        ],
        _id: '6611dc5bceba479b0ce476fc',
      },
      {
        questionTitle: '14. Cho hình bên dưới',
        image: 'https://i.imghippo.com/files/6IGGs1714706771.jpg',
        options: [
          {
            content: 'A',
            isResult: true,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce47707',
          },
          {
            content: 'B',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce47708',
          },
          {
            content: 'C',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce47709',
          },
          {
            content: 'D',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce4770a',
          },
        ],
        _id: '6611dc5bceba479b0ce47706',
      },
      {
        questionTitle: '15. Số nào sẽ thay cho dấu chấm hỏi?',
        image: 'https://i.imghippo.com/files/9Svjm1714706939.jpg',
        options: [
          {
            content: 'A. 17',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce4770c',
          },
          {
            content: 'B. 31',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce4770d',
          },
          {
            content: 'C. 16',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce4770e',
          },
          {
            content: 'D. 6',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce4770f',
          },
        ],
        _id: '6611dc5bceba479b0ce4770b',
      },
      {
        questionTitle: '16. Cho hình bên dưới?',
        image: 'https://i.imghippo.com/files/9MPTo1714707058.jpg',
        options: [
          {
            content: 'A',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce47711',
          },
          {
            content: 'B',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce47712',
          },
          {
            content: 'C',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce47713',
          },
          {
            content: 'D',
            isResult: true,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce47714',
          },
        ],
        _id: '6611dc5bceba479b0ce47710',
      },
      {
        questionTitle: '17. Trong 4 loại sau đây, loại nào có đặc tính ít giống với 3 loại còn lại?',
        options: [
          {
            content: 'A. Tỏi',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce47716',
          },
          {
            content: 'B.Nho',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce47717',
          },
          {
            content: 'C. Rau diếp cá',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce47718',
          },
          {
            content: 'D. Nấm',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce47719',
          },
        ],
        _id: '6611dc5bceba479b0ce47715',
      },
      {
        questionTitle:
          '18. Hình lục giác nào trong số các hình A, B, C, D và E có thể thêm vào một dấu chấm sao cho đáp ứng được cùng điều kiện như trong hình lục giác bên trên 5 hình này ?',
        image: 'https://i.imghippo.com/files/VAj0A1714707210.jpg',
        options: [
          {
            content: 'A',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce4771b',
          },
          {
            content: 'B',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce4771c',
          },
          {
            content: 'C',
            isResult: false,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce4771d',
          },
          {
            content: 'E',
            isResult: true,
            standardScore: 10,
            _id: '6611dc5bceba479b0ce4771e',
          },
        ],
        _id: '6611dc5bceba479b0ce4771a',
      },
      {
        questionTitle: '19. Số nào khác tính chất với các số còn lại',
        options: [
          {
            content: 'A. 5261',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce47720',
          },
          {
            content: '3527',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce47721',
          },
          {
            content: '7768',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce47722',
          },
          {
            content: '6895',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce47723',
          },
        ],
        _id: '6611dc5bceba479b0ce4771f',
      },
      {
        questionTitle: '20. Số tiếp theo của chuỗi số sau: 0, 1, 2, 6, 9, 12, 16',
        options: [
          {
            content: 'A. 20',
            isResult: true,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce47725',
          },
          {
            content: 'B.18',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce47726',
          },
          {
            content: 'C. 22',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce47727',
          },
          {
            content: 'D. 24',
            isResult: false,
            standardScore: 5,
            _id: '6611dc5bceba479b0ce47728',
          },
        ],
        _id: '6611dc5bceba479b0ce47724',
      },
    ],
    results: [
      {
        score: [0, 54],
        content: 'Trung bình',
        _id: '6611dc5bceba479b0ce47729',
      },
      {
        score: [54, 72],
        content: 'Giỏi',
        _id: '6611dc5bceba479b0ce4772a',
      },
      {
        score: [72, 90],
        content: 'Rất giỏi',
        _id: '6611dc5bceba479b0ce4772b',
      },
      {
        score: [90, 105],
        content: 'Xuất sắc',
        _id: '6611dc5bceba479b0ce4772c',
      },
      {
        score: [105, 120],
        content: 'Rất xuất sắc',
        _id: '6611dc5bceba479b0ce4772d',
      },
    ],
  },
];
